version: '2'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        command: [nginx-debug, '-g', 'daemon off;']
        links:
            - crearcliente
            - consultarcliente
            - modificarcliente
            - eliminarcliente
            - creararticulo
            - consultararticulo
            - modificararticulo
            - eliminararticulo
        ports:
            - "8080:8080"
        
    crearcliente:
        build: ./cliente

    consultarcliente:
        build: ./cliente

    modificarcliente:
        build: ./cliente

    eliminarcliente:
        build: ./cliente

    creararticulo:
        build: ./inventario

    consultararticulo:
        build: ./inventario

    modificararticulo:
        build: ./inventario

    eliminararticulo:
        build: ./inventario